version: '3.11'

services:

  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_diploma_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

volumes:
  pg_diploma_data:
